const engine=createHealthcareEngine();
const $=id=>document.getElementById(id);
let map,workmap,routeLayer,originLayer,ambulanceMarker,closureLayer,activeClosure=null;
const villages=engine.nodes.filter(n=>n.type==='VILLAGE');
function clock(){ $('clock').textContent=new Date().toLocaleTimeString('en-GB'); }
setInterval(clock,1000); clock();
function edgeCount(){let n=0;engine.graph.forEach(e=>n+=e.length);return Math.round(n/2)}
function log(msg,type=''){const el=document.createElement('div');el.className='log '+type;el.textContent=msg;$('log').prepend(el);if(window.gsap)gsap.from(el,{y:8,opacity:0,duration:.35,ease:'power2.out'})}
function toast(k,t){$('toastK').textContent=k;$('toastT').textContent=t;$('toast').style.display='block';if(window.gsap){gsap.fromTo('#toast',{y:18,opacity:0},{y:0,opacity:1,duration:.35});gsap.delayedCall(3,()=>gsap.to('#toast',{y:18,opacity:0,duration:.3,onComplete:()=>$('toast').style.display='none'}))}}
function hospitalUI(){const box=$('hospitals');box.innerHTML='';engine.hospitals.forEach(h=>{const el=document.createElement('div');el.className='hospital';el.dataset.id=h.id;const sp=h.specialty.join(' · ');const bed=Math.round(Math.min(100,h.beds/20*100));const med=Math.round(Math.min(100,h.medicine/100*100));el.innerHTML=`<div class="hrow"><span class="hid">${h.id}</span><span class="spec">${sp}</span></div><div class="bars"><div><div class="barlabel"><span>BEDS</span><b>${h.beds}</b></div><div class="bar"><i style="width:${bed}%"></i></div></div><div><div class="barlabel"><span>MED</span><b>${h.medicine}</b></div><div class="bar meds"><i style="width:${med}%"></i></div></div></div>`;box.appendChild(el)})}
function fleetUI(){const box=$('fleet');box.innerHTML='';let idle=0;engine.ambulances.forEach(a=>{if(a.status==='IDLE')idle++;const el=document.createElement('i');el.className='unit'+(a.status==='DISPATCHED'?' active':'');el.title=a.id+' · '+a.status;box.appendChild(el)});$('fleetCount').textContent=`${idle} IDLE · ${10-idle} ACTIVE`}
function addMarkers(target){engine.nodes.forEach(n=>{if(n.type==='VILLAGE')L.circleMarker(n.coordinates,{radius:2.2,color:'#566d70',fillColor:'#8aa0a2',fillOpacity:.55,weight:0}).addTo(target)});engine.hospitals.forEach(h=>{const icon=L.divIcon({className:'',html:'<div style="width:12px;height:12px;background:#65e6e2;border:2px solid #d2fffd;transform:rotate(45deg);box-shadow:0 0 18px rgba(101,230,226,.8)"></div>',iconSize:[12,12],iconAnchor:[6,6]});L.marker(h.coordinates,{icon}).addTo(target).bindTooltip(h.id,{direction:'top',offset:[0,-7]})})}
function tacticalTiles(){const layer=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',subdomains:['a','b','c'],maxZoom:19,crossOrigin:true,keepBuffer:2,updateWhenIdle:true,updateWhenZooming:false});layer.on('tileerror',e=>{const tile=e?.tile;if(tile){tile.dataset.networkFault='1';tile.style.opacity='.82'}});return layer}
function mapOptions(){return{preferCanvas:true,zoomControl:false,touchZoom:true,dragging:true,doubleClickZoom:true,tapTolerance:18,boxZoom:false}}
function initMap(){const opts=mapOptions();map=L.map('map',opts).setView([19,73],10);tacticalTiles().addTo(map);map.scrollWheelZoom.disable();addMarkers(map);$('edgeCount').textContent=edgeCount();workmap=L.map('workmap',opts).setView([19,73],10);tacticalTiles().addTo(workmap);addMarkers(workmap);setTimeout(()=>{map.invalidateSize();workmap.invalidateSize()},200)}
function chooseDemo(){for(const s of ['Cardiology','Trauma','Neurology','Pediatrics']){const h=engine.hospitals.find(x=>x.specialty.includes(s)&&x.beds>0&&x.medicine>0);if(h)return{specialty:s,hospital:h}}return{specialty:'Cardiology',hospital:engine.hospitals[0]}}
function originFor(h){let best=villages[0],bestD=Infinity;villages.forEach(v=>{const dx=v.coordinates[0]-h.coordinates[0],dy=v.coordinates[1]-h.coordinates[1],d=dx*dx+dy*dy;if(d<bestD){best=v;bestD=d}});return best}
function refreshSpecialties(){const available=[...new Set(engine.hospitals.flatMap(h=>h.specialty))];const sel=$('specialty');[...sel.options].forEach(o=>o.disabled=!available.includes(o.value));sel.value=chooseDemo().specialty}
function clearVisuals(){if(routeLayer){workmap.removeLayer(routeLayer);routeLayer=null}if(originLayer){workmap.removeLayer(originLayer);originLayer=null}if(ambulanceMarker){workmap.removeLayer(ambulanceMarker);ambulanceMarker=null}if(closureLayer){workmap.removeLayer(closureLayer);closureLayer=null}}
function drawRoute(result,origin){clearVisuals();const pts=result.path.map(id=>engine.nodes.find(n=>n.id===id).coordinates);routeLayer=L.polyline(pts,{color:'#65e6e2',weight:4,opacity:.95,className:'route-glow'}).addTo(workmap);originLayer=L.circleMarker(origin.coordinates,{radius:6,color:'#f4bd67',fillColor:'#f4bd67',fillOpacity:1,weight:2}).addTo(workmap);const a=engine.ambulances.find(x=>x.id===result.ambulance.id);const an=engine.nodes.find(n=>n.id===a.currentNode);ambulanceMarker=L.circleMarker(an.coordinates,{radius:6,color:'#ff6571',fillColor:'#ff6571',fillOpacity:1,weight:2}).addTo(workmap);workmap.fitBounds(routeLayer.getBounds().pad(.18),{animate:true,duration:.8});if(routeLayer._path&&window.gsap)gsap.from(routeLayer._path,{strokeDashoffset:220,duration:1.2,ease:'power2.out'})}
function dispatch(){const btn=$('dispatch');btn.disabled=true;$('mode').textContent='COMPUTING';$('mode').style.color='var(--amber)';log('Emergency request accepted. Starting weighted graph search.');const specialty=$('specialty').value;const h=engine.hospitals.find(x=>x.specialty.includes(specialty)&&x.beds>0&&x.medicine>0)||engine.hospitals.find(x=>x.beds>0&&x.medicine>0);const origin=originFor(h);$('origin').textContent=origin.id;setTimeout(()=>{let result=engine.processEmergency(origin.id,specialty);if(!result.success){const fallback=chooseDemo();$('specialty').value=fallback.specialty;result=engine.processEmergency(origin.id,fallback.specialty)}if(result.success){drawRoute(result,origin);result.decisionLog.forEach((x,i)=>log(x,i===result.decisionLog.length-1?'success':''));$('mode').textContent='DISPATCHED';$('mode').style.color='var(--lime)';$('mapState').textContent='ROUTE LOCKED';$('mapSub').textContent=`${result.hospital.id} · ${result.ambulance.id} · COST ${result.compositeCost}`;$('mission').className='mission show';$('mission').innerHTML=`<div class="mission-kicker">ACTIVE MISSION</div><div class="mission-main"><span>${result.ambulance.id} → ${result.hospital.id}</span><span class="mission-cost">${result.compositeCost}</span></div><div class="mission-meta">TRAVEL ${result.travelTime} · WAIT PENALTY ${result.waitPenalty} · ${result.algorithm}</div>`;document.querySelectorAll('.hospital').forEach(el=>el.classList.toggle('active',el.dataset.id===result.hospital.id));toast('DISPATCH AUTHORIZED',`${result.ambulance.id} routed to ${result.hospital.id}`);if(window.gsap)gsap.from('.mission',{y:12,opacity:0,duration:.5,ease:'back.out(1.5)'})}else{result.decisionLog?.forEach(x=>log(x,'warn'));$('mode').textContent='QUEUED';$('mode').style.color='var(--amber)';toast('NO FEASIBLE ROUTE','Request held for operator review')}fleetUI();hospitalUI();btn.disabled=false},650)}
function closure(){if(activeClosure){engine.setRoadBlocked(activeClosure[0],activeClosure[1],false);activeClosure=null;if(closureLayer)workmap.removeLayer(closureLayer);closureLayer=null;log('Road closure cleared. Network restored.');$('mapState').textContent='LIVE NETWORK';$('mapSub').textContent='500 NODES · 1 ACTIVE SCENARIO';toast('ROAD RESTORED','Routing graph returned to normal');return}const a=engine.nodes[Math.floor(Math.random()*engine.nodes.length)],neighbors=engine.graph.get(a.id)||[];if(!neighbors.length)return;const b=engine.nodes.find(n=>n.id===neighbors[0].to);engine.setRoadBlocked(a.id,b.id,true);activeClosure=[a.id,b.id];closureLayer=L.polyline([a.coordinates,b.coordinates],{color:'#f4bd67',weight:5,dashArray:'5 8',opacity:.9}).addTo(workmap);log(`Road closure injected between ${a.id} and ${b.id}. Dijkstra will avoid it.`,'warn');$('mapState').textContent='ROAD CLOSURE ACTIVE';$('mapSub').textContent=`${a.id} ↔ ${b.id} · ALTERNATE PATH REQUIRED`;toast('ROAD CLOSURE','Graph edge marked unavailable')}
function resetFleet(){engine.ambulances.forEach(a=>a.status='IDLE');clearVisuals();fleetUI();hospitalUI();$('mission').className='mission';$('mode').textContent='READY';$('mode').style.color='var(--lime)';$('mapState').textContent='LIVE NETWORK';$('mapSub').textContent='500 NODES · 1 ACTIVE SCENARIO';log('Fleet reset. All ambulances available for dispatch.','success');toast('FLEET RESET','10 ambulances returned to idle')}
$('enterCommand').addEventListener('click',()=>document.querySelector('#command').scrollIntoView({behavior:'smooth'}));$('dispatch').addEventListener('click',dispatch);$('closure').addEventListener('click',closure);$('resetFleet').addEventListener('click',resetFleet);$('clear').addEventListener('click',()=>$('log').innerHTML='');
window.addEventListener('load',()=>{initMap();hospitalUI();fleetUI();refreshSpecialties();log('Network initialized. 500 nodes loaded.','success');log('Waiting for incoming emergency request.');if(window.gsap)gsap.from('.reveal',{y:34,opacity:0,duration:1,stagger:.09,ease:'power3.out',delay:.15})});
window.addEventListener('resize',()=>{if(map)map.invalidateSize();if(workmap)workmap.invalidateSize()});
window.addEventListener('load',()=>{const architecture=document.createElement('script');architecture.src='/architecture-pass.js?v=20260826c';architecture.onload=()=>{const hooks=document.createElement('script');hooks.src='/architecture-hooks.js?v=20260826e';hooks.defer=true;document.head.appendChild(hooks)};architecture.defer=true;document.head.appendChild(architecture)},{once:true});