(()=>{
'use strict';
const boot=()=>{
 if(window.__MEDROUTE_DIRECTOR__)return;window.__MEDROUTE_DIRECTOR__=true;
 const e=window.__MEDROUTE_ENGINE__;if(!e)return;
 const style=document.createElement('style');style.id='mr-director-style';style.textContent=`
:root{--mr-bg:#030407;--mr-cyan:#06b6d4;--mr-indigo:#4f46e5;--mr-red:#f43f5e;--mr-amber:#f59e0b}
body{background:var(--mr-bg)}
body:before{z-index:2;opacity:.28}
.mr-ambient{position:fixed;inset:0;z-index:3;pointer-events:none;overflow:hidden;mix-blend-mode:screen}.mr-ambient i{position:absolute;width:42vw;height:42vw;border-radius:50%;filter:blur(70px);opacity:.12;transform:translate3d(0,0,0);will-change:transform}.mr-ambient .a{left:-16vw;top:8vh;background:#4f46e5}.mr-ambient .b{right:-18vw;top:12vh;background:#06b6d4}.mr-ambient .c{right:14vw;bottom:-24vw;background:#7c3aed}.mr-ambient.incident .a{background:#f43f5e}.mr-ambient.incident .b{background:#f59e0b}.mr-ambient.incident .c{background:#f43f5e}.mr-ambient.incident i{opacity:.22;animation:mrPulseGlow .75s ease-in-out infinite alternate}
.hero{background:radial-gradient(circle at 56% 38%,rgba(6,182,212,.035),transparent 35%);isolation:isolate}.hero h1,.hero h1 em{transform:none!important;will-change:auto!important;animation:mrTitleFlow 6s ease-in-out infinite!important;text-rendering:geometricPrecision;-webkit-font-smoothing:antialiased}.hero h1{color:#f7fffe!important;text-shadow:0 0 1px rgba(255,255,255,.8),0 18px 80px rgba(0,0,0,.55)}.hero h1 em{display:inline-block;color:transparent!important;background:linear-gradient(105deg,#61e7e1 0%,#a5f3fc 24%,#c8ff75 48%,#fff 62%,#06b6d4 82%,#61e7e1 100%)!important;background-size:260% 100%!important;-webkit-background-clip:text!important;background-clip:text!important}.hero p{color:#c6d5d4!important}.actions .primary,.actions .secondary,.dispatch,.tool{transform:translate3d(0,0,0);will-change:transform}.heroHUD,.card,.shell,.panel,.maphud,.legend,.benchbox{background:linear-gradient(145deg,rgba(11,20,26,.78),rgba(3,7,10,.66));border-color:rgba(224,246,244,.11);box-shadow:inset 0 1px rgba(255,255,255,.045),0 25px 90px rgba(0,0,0,.3)}
.grid{grid-template-columns:repeat(12,minmax(0,1fr));gap:10px}.mapwork{grid-column:span 8;min-width:0}.panel{grid-column:span 4;min-width:0}.cards{grid-template-columns:repeat(12,minmax(0,1fr));gap:10px;border:0}.card{grid-column:span 4;border:1px solid rgba(224,246,244,.1)!important}.card:nth-child(2){grid-column:span 5}.card:nth-child(3){grid-column:span 3}
.leaflet-container{filter:saturate(.62) contrast(1.14) brightness(.78)!important}.leaflet-tile{filter:invert(1) hue-rotate(178deg) saturate(.35) brightness(.72) contrast(1.16)}.mapwork:before{content:"";position:absolute;inset:0;z-index:797;pointer-events:none;background:radial-gradient(circle at 50% 50%,transparent 20%,rgba(0,0,0,.08) 55%,rgba(0,0,0,.42) 100%),linear-gradient(rgba(97,231,225,.025) 1px,transparent 1px),linear-gradient(90deg,rgba(97,231,225,.025) 1px,transparent 1px);background-size:100% 100%,44px 44px,44px 44px}.maphud,.legend{box-shadow:inset 0 1px rgba(255,255,255,.06),0 15px 50px rgba(0,0,0,.35)}
.leaflet-marker-icon>div{position:relative!important;border-radius:50%!important;transform:rotate(45deg);box-shadow:0 0 16px rgba(97,231,225,.75),0 0 0 1px rgba(255,255,255,.35)!important}.leaflet-marker-icon>div:before,.leaflet-marker-icon>div:after{content:"";position:absolute;inset:-7px;border:1px solid rgba(97,231,225,.32);border-radius:50%;animation:mrBeacon 2.2s ease-out infinite}.leaflet-marker-icon>div:after{inset:-15px;animation-delay:1.1s}
.route{stroke:#6ff7ee!important;stroke-width:6!important;filter:drop-shadow(0 0 4px #6ff7ee) drop-shadow(0 0 18px rgba(97,231,225,.7));stroke-dasharray:10 13;animation:mrRoute .42s linear infinite,mrRouteGlow 1.4s ease-in-out infinite}.mr-incident .route{stroke:#ffb35c!important;filter:drop-shadow(0 0 5px #ff6472) drop-shadow(0 0 22px rgba(255,101,114,.72))}.mr-incident .mapwork:before{background:radial-gradient(circle at 50% 50%,transparent 18%,rgba(255,80,70,.05) 50%,rgba(0,0,0,.5) 100%),linear-gradient(rgba(255,150,80,.025) 1px,transparent 1px),linear-gradient(90deg,rgba(255,150,80,.025) 1px,transparent 1px);background-size:100% 100%,44px 44px,44px 44px}
.mr-command-palette{z-index:14000!important}.mr-cursor{z-index:15000!important}
.mr-director-latency{position:fixed;right:18px;top:82px;z-index:850;padding:7px 9px;border:1px solid rgba(97,231,225,.14);background:rgba(3,6,9,.68);backdrop-filter:blur(10px);font:6px 'IBM Plex Mono';letter-spacing:.1em;color:#607779;pointer-events:none}.mr-director-latency b{color:#9feee9}.mr-director-latency .ok{color:#baf36d}.mr-director-latency .hot{color:#ff8790}
.mr-reticle-lock{transform:scale(.78) rotate(90deg)!important;transition:transform .35s cubic-bezier(.22,1,.36,1)}
@keyframes mrTitleFlow{0%,100%{background-position:0 50%}50%{background-position:100% 50%}}@keyframes mrBeacon{0%{transform:scale(.45);opacity:.75}100%{transform:scale(1.45);opacity:0}}@keyframes mrRoute{to{stroke-dashoffset:-23}}@keyframes mrRouteGlow{50%{filter:drop-shadow(0 0 10px #6ff7ee) drop-shadow(0 0 30px rgba(97,231,225,.72))}}@keyframes mrPulseGlow{to{transform:scale(1.08);opacity:.34}}@media(max-width:900px){.grid{display:block!important}.mapwork{min-height:58vh}.panel{min-height:0}.cards{grid-template-columns:1fr}.card,.card:nth-child(2),.card:nth-child(3){grid-column:auto}.mr-director-latency{top:68px;right:10px;font-size:5.5px}.hero h1{font-size:clamp(56px,15vw,102px)!important;line-height:.84!important}.leaflet-tile{filter:invert(1) hue-rotate(178deg) saturate(.28) brightness(.65) contrast(1.1)}}@media(max-width:560px){.mr-ambient i{filter:blur(45px);opacity:.08}.mr-director-latency{display:none}.mapwork{min-height:48vh!important;height:48vh!important}.hero h1{font-size:clamp(48px,16.5vw,76px)!important;line-height:.86!important}.leaflet-marker-icon>div:before,.leaflet-marker-icon>div:after{display:none}.mr-ambient .c{display:none}}
`;document.head.appendChild(style);
 const amb=document.createElement('div');amb.className='mr-ambient';amb.innerHTML='<i class="a"></i><i class="b"></i><i class="c"></i>';document.body.prepend(amb);
 const latency=document.createElement('div');latency.className='mr-director-latency';latency.innerHTML='ENGINE <b>ONLINE</b> · UI <b id="mrFps">-- FPS</b> · LAT <b id="mrLat">--</b>';document.body.appendChild(latency);
 let last=performance.now(),frames=0;const fps=()=>{frames++;const now=performance.now();if(now-last>900){const f=Math.round(frames*1000/(now-last));document.getElementById('mrFps').textContent=f+' FPS';frames=0;last=now}};requestAnimationFrame(function loop(){fps();requestAnimationFrame(loop)});
 const mode=document.getElementById('mode');const sync=()=>{const text=(mode?.textContent||'READY').toUpperCase();const incident=/COMPUTING|DISPATCHED|ROUTE|QUEUED|CLOSURE/.test(text);document.body.classList.toggle('mr-incident',incident);amb.classList.toggle('incident',incident);if(window.__MEDROUTE_AUDIO__?.critical&&text==='DISPATCHED'&&!amb.dataset.alert){amb.dataset.alert='1';window.__MEDROUTE_AUDIO__.critical();setTimeout(()=>delete amb.dataset.alert,1200)}else if(!incident)delete amb.dataset.alert};if(mode){new MutationObserver(sync).observe(mode,{childList:true,characterData:true,subtree:true});sync()}
 const interactive=()=>document.querySelectorAll('button,.hospital,.tool,.primary,.secondary');const lock=()=>{const c=document.querySelector('.mr-cursor');interactive().forEach(el=>{if(el.dataset.directorBound)return;el.dataset.directorBound='1';el.addEventListener('pointerenter',()=>{c?.classList.add('mr-reticle-lock');if(window.gsap)gsap.to(c,{scale:.78,rotation:90,duration:.3,ease:'back.out(2)'})});el.addEventListener('pointerleave',()=>{c?.classList.remove('mr-reticle-lock');if(window.gsap)gsap.to(c,{scale:1,rotation:0,duration:.45,ease:'elastic.out(1,.55)'})})})};setTimeout(lock,900);setInterval(lock,1800);
 class RTreeLite{constructor(){this.items=[]}insert(item){this.items.push(item)}search(lat,lng,r=0.1){const minLat=lat-r,maxLat=lat+r,minLng=lng-r,maxLng=lng+r;return this.items.filter(x=>x.lat>=minLat&&x.lat<=maxLat&&x.lng>=minLng&&x.lng<=maxLng)}}
 const index=new RTreeLite();e.hospitals.forEach(h=>index.insert({id:h.id,lat:h.coordinates[0],lng:h.coordinates[1],ref:h}));window.__MEDROUTE_HOSPITAL_INDEX__=index;window.__MEDROUTE_SPATIAL_QUERY__=(lat,lng,r)=>index.search(lat,lng,r);
 const stamp=()=>{const n=document.querySelectorAll('.mr-scramble,.hudvalue,.result .big,.meta b');n.forEach(el=>el.classList.add('mr-scramble'));};stamp();new MutationObserver(stamp).observe(document.body,{subtree:true,childList:true});
 window.addEventListener('error',ev=>{if(document.getElementById('mrDirectorFault'))return;const x=document.createElement('div');x.id='mrDirectorFault';x.textContent='UI FAULT CONTAINED · CORE ROUTER REMAINS ONLINE';Object.assign(x.style,{position:'fixed',left:'50%',bottom:'18px',transform:'translateX(-50%)',zIndex:16000,padding:'8px 12px',background:'#18090d',border:'1px solid #ff6472',color:'#ff9aa3',font:'7px IBM Plex Mono'});document.body.appendChild(x);setTimeout(()=>x.remove(),5000)});
};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else setTimeout(boot,80);
})();