(()=>{
const boot=()=>{
  if(window.__MEDROUTE_FINAL_POLISH__) return; window.__MEDROUTE_FINAL_POLISH__=true;
  const $=id=>document.getElementById(id), logs=$('logs'); if(!logs) return;
  const style=document.createElement('style'); style.textContent=`
  .logs{padding-right:4px}.timeline{position:relative}.timeline:after{content:'LIVE DECISION TRACE';position:absolute;right:19px;top:15px;font:6px 'IBM Plex Mono';letter-spacing:.16em;color:#456063;pointer-events:none}
  .trace{border:1px solid rgba(224,246,244,.09);background:linear-gradient(135deg,#ffffff04,#61e7e106);margin:8px 0 10px;padding:10px 11px;border-radius:2px;box-shadow:inset 2px 0 #61e7e155}.trace-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:7px}.trace-id{font:700 7px 'IBM Plex Mono';letter-spacing:.13em;color:#9feee9}.trace-time{font:6px 'IBM Plex Mono';color:#4e6466}.trace-row{display:grid;grid-template-columns:72px 1fr;gap:7px;padding:4px 0;border-top:1px solid #ffffff06}.trace-tag{font:6px 'IBM Plex Mono';letter-spacing:.08em;color:#5f7678}.trace-msg{font:7px/1.45 'IBM Plex Mono';color:#91a6a7}.trace-row.good .trace-msg{color:#a9e7e3}.trace-row.warn .trace-msg{color:#f1bf6b}.trace-row.bad .trace-msg{color:#ff8790}.trace-row.decision{border-top-color:#61e7e11c;background:#61e7e105}.trace-row.decision .trace-msg{color:#cce9e7}.trace-row.mutation .trace-msg{color:#baf36d}.trace-row.locked{margin:5px -3px 0;padding:7px 5px;border:1px solid #61e7e133;background:#61e7e108}.trace-row.locked .trace-msg{color:#61e7e1;font-weight:600}.legacy-log{display:none!important}
  @media(max-width:560px){.timeline{min-height:230px;padding:12px}.timeline:after{position:static;display:block;margin-bottom:5px}.trace{padding:9px}.trace-row{grid-template-columns:64px 1fr}.trace-msg{font-size:6.5px}}
  `;document.head.appendChild(style);
  let active=null, seq=0;
  const classify=(t,k)=>{const u=t.toUpperCase(); if(u.startsWith('REQUEST /'))return ['REQUEST','request']; if(u.includes('DIJKSTRA')||u.includes('REJECTED')||u.includes('EXCEEDS')||u.includes('LACKS')||u.includes('INFEASIBLE'))return ['EVALUATION',k||'warn']; if(u.includes('ROUTED TO')||u.includes('FINAL COMPOSITE')||u.includes('LOWEST')||u.includes('REROUT'))return ['DECISION','decision']; if(u.includes('BEDS REMAINING')||u.includes('MEDICINE REMAINING')||u.includes('AMB-')||u.includes('MEDICINE QUEUE'))return ['STATE UPDATE','mutation']; if(u.includes('ROUTE LOCKED')||u.includes('DISPATCH /'))return ['DISPATCH','locked']; if(u.includes('FAILED')||u.includes('ERROR'))return ['RESULT','bad']; return ['SYSTEM',''];};
  const structured=(t,k='')=>{const [tag,auto]=classify(String(t),k); if(tag==='REQUEST'){seq++;active=document.createElement('div');active.className='trace';active.innerHTML=`<div class="trace-head"><span class="trace-id">EMERGENCY TRACE / ${String(seq).padStart(2,'0')}</span><span class="trace-time">${new Date().toLocaleTimeString([], {hour12:false})}</span></div>`;logs.appendChild(active)}
    if(!active){const row=document.createElement('div');row.className='trace-row '+auto;row.innerHTML=`<span class="trace-tag">${tag}</span><span class="trace-msg"></span>`;row.querySelector('.trace-msg').textContent=t;logs.appendChild(row);logs.scrollTop=logs.scrollHeight;return}
    const row=document.createElement('div');row.className='trace-row '+auto;row.innerHTML=`<span class="trace-tag">${tag}</span><span class="trace-msg"></span>`;row.querySelector('.trace-msg').textContent=String(t).replace(/^REQUEST\s*\/\s*/i,'');active.appendChild(row);logs.scrollTop=logs.scrollHeight;
    if(window.gsap)gsap.from(row,{x:8,opacity:0,duration:.18});
  };
  window.log=structured;
  // Watchdog: a visualization exception must never leave the primary action permanently disabled.
  setInterval(()=>{const b=$('dispatch');if(b&&b.disabled&&/COMPUTING/i.test(b.textContent||'')){const since=Number(b.dataset.computeSince||0);if(!since)b.dataset.computeSince=String(Date.now());else if(Date.now()-since>12000){b.disabled=false;b.textContent='AUTHORIZE DISPATCH';$('mapStatus')&&($('mapStatus').textContent='READY · COMPUTATION RECOVERED');structured('DISPATCH RECOVERY / computation exceeded 12s; controls restored','bad');delete b.dataset.computeSince}}else if(b)delete b.dataset.computeSince},1000);
};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else setTimeout(boot,0);
})();
