'use strict';

function heapPush(heap,item){heap.push(item);let i=heap.length-1;while(i){const p=(i-1)>>1;if(heap[p].d<=heap[i].d)break;[heap[p],heap[i]]=[heap[i],heap[p]];i=p}}
function heapPop(heap){if(!heap.length)return null;if(heap.length===1)return heap.pop();const x=heap[0];heap[0]=heap.pop();let i=0;for(;;){const l=i*2+1,r=l+1;let s=i;if(l<heap.length&&heap[l].d<heap[s].d)s=l;if(r<heap.length&&heap[r].d<heap[s].d)s=r;if(s===i)break;[heap[i],heap[s]]=[heap[s],heap[i]];i=s}return x}
function key(a,b){return `${a}|${b}`}
function dijkstra(graph,start,target,bannedNodes,bannedEdges){const dist=new Map([[start,0]]),prev=new Map(),q=[];heapPush(q,{n:start,d:0});while(q.length){const cur=heapPop(q);if(!cur||cur.d!==dist.get(cur.n))continue;if(cur.n===target)break;for(const e of graph[cur.n]||[]){if(bannedNodes.has(e.to)||bannedEdges.has(key(cur.n,e.to)))continue;const nd=cur.d+e.w;if(nd<(dist.get(e.to)??Infinity)){dist.set(e.to,nd);prev.set(e.to,cur.n);heapPush(q,{n:e.to,d:nd})}}}if(!dist.has(target))return null;const path=[];for(let n=target;n!==undefined;n=prev.get(n)){path.push(n);if(n===start)break}path.reverse();return path[0]===start?{path,cost:dist.get(target)}:null}
function samePrefix(a,b,n){for(let i=0;i<n;i++)if(a[i]!==b[i])return false;return true}
function yen(graph,start,target,k){const first=dijkstra(graph,start,target,new Set(),new Set());if(!first)return[];const A=[first],B=[],seen=new Set([first.path.join('>')]);for(let rank=1;rank<k;rank++){const prevPath=A[rank-1].path;for(let i=0;i<prevPath.length-1;i++){const spur=prevPath[i],root=prevPath.slice(0,i+1),rootKey=root.join('>');const bannedEdges=new Set(),bannedNodes=new Set(root.slice(0,-1));for(const p of A){if(p.path.length>i&&samePrefix(p.path,root,i+1))bannedEdges.add(key(p.path[i],p.path[i+1]))}const spurResult=dijkstra(graph,spur,target,bannedNodes,bannedEdges);if(!spurResult)continue;const totalPath=root.slice(0,-1).concat(spurResult.path);const id=totalPath.join('>');if(seen.has(id))continue;let rootCost=0;for(let j=0;j<root.length-1;j++){const edge=(graph[root[j]]||[]).find(e=>e.to===root[j+1]);if(!edge){rootCost=Infinity;break}rootCost+=edge.w}const candidate={path:totalPath,cost:rootCost+spurResult.cost};B.push(candidate);seen.add(id)}if(!B.length)break;B.sort((a,b)=>a.cost-b.cost);A.push(B.shift())}return A}
self.onmessage=e=>{const {type,graph,start,target,k=3}=e.data||{};if(type!=='k-shortest')return;try{const paths=yen(graph,start,target,Math.max(1,Math.min(3,k)));self.postMessage({type:'k-shortest-result',paths})}catch(error){self.postMessage({type:'error',message:String(error?.message||error)})}};
