const assert=require('node:assert/strict');
const {MinPriorityQueue,createHealthcareEngine,SPECIALTIES}=require('./core-engine.js');
const q=new MinPriorityQueue();q.enqueue('slow',20);q.enqueue('fast',3);q.enqueue('mid',11);assert.equal(q.dequeue().value,'fast');assert.equal(q.dequeue().value,'mid');assert.equal(q.dequeue().value,'slow');
const engine=createHealthcareEngine();const village=engine.nodes.find(n=>n.type==='VILLAGE');assert(village);assert.equal(engine.nodes.length,500);assert.equal(engine.hospitals.length,5);assert.equal(engine.ambulances.length,10);
const before=engine.hospitals.map(h=>[h.beds,h.medicine]);const invalid=engine.processEmergency('NOT-A-NODE','Cardiology');assert.equal(invalid.success,false);assert.equal(invalid.status,'INVALID_REQUEST');assert.deepEqual(engine.hospitals.map(h=>[h.beds,h.medicine]),before);
const specialty=engine.hospitals[0].specialty[0]||SPECIALTIES[0];const result=engine.processEmergency(village.id,specialty,{urgency:'NORMAL',timeWindow:Infinity,patientId:'TEST-001'});assert.equal(result.success,true);assert.equal(result.status,'DISPATCHED');assert(result.path.length>=2);assert.equal(result.ambulance.status,'DISPATCHED');const idx=engine.hospitals.findIndex(h=>h.id===result.hospital.id);assert.equal(result.hospital.beds,before[idx][0]-1);assert.equal(result.hospital.medicine,before[idx][1]-1);assert.equal(result.medicineTask.status,'PREPARED');assert.equal(engine.medicineQueue.length,1);
engine.ambulances.forEach(a=>a.status='DISPATCHED');const exhausted=engine.processEmergency(village.id,specialty);assert.equal(exhausted.success,false);assert.equal(exhausted.status,'QUEUED_NO_AMBULANCE');
const engine2=createHealthcareEngine();const v2=engine2.nodes.find(n=>n.type==='VILLAGE');for(let i=0;i<25;i++)engine2.queueEmergency({startNode:v2.id,requiredSpecialty:engine2.hospitals[0].specialty[0],urgency:i%3===0?'CRITICAL':i%3===1?'HIGH':'NORMAL'});assert.equal(engine2.getMetrics().queue,25);const batch=engine2.processQueuedEmergencies(25);assert.equal(batch.length,25);assert(engine2.getMetrics().completed<=25);
console.log('MED-ROUTE production engine tests: PASS');
